version: "3.3"

services:
  instatom:
    container_name: livewedding
    build: .
    environment:
      - PORT=4032
      - REDIS_URL=redis://redis:6379
    expose:
      - 4032
    ports:
    - "4032:4032"
    volumes:
      - .:/usr/src/app
      - "/usr/src/app/node_modules"
  redis:
    image: redis:3.2.11
    ports:
      - '6379:6379'
